### ISSUE TITLE
DTRIAC NLP Pipeline

### ISSUE THREAD

**Issue by keighrim** [brandeis-llc/dtriac-pipeline#10]
With the new set of data (`19d`) that has very different characteristics from data used in the June demo (`534`), we need to re-think the NLP pipeline we'll use for the upcoming demo.

**Comment by marcverhagen** [comment]
Starting from the raw tesseract output, here is the size (only printing the last line):

```
$ wc /data/dtriac/dtriac-19d/all/*/tesseract-300dpi-20p.txt 
13958734  63579505 400100406 total
```

Pipeline:
- [x] convert into LIF
- [x] topic model
- [ ] CoreNLP NER, Splitter and POS
- [ ] mark sentences with crap
- [ ] gazetteer lookup
- [ ] finding authors and titles and publication date
- [ ] technologies
- [ ] creating JSON files for ELK
